apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-microservice
  annotations:
    scheduling.k8s.io/v1: low-priority
spec:
  selector:
    matchLabels:
      app: auth-microservice
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-microservice
    spec:
      containers:
      - name: auth-microservice
        image: registry.hub.docker.com/linhhnbkdn/auth-miroservice:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "256m"
        command: ["python", "/auth/manage.py", "runserver", "0.0.0.0:8000"]
        # command: ["sleep", "infinity"]
        volumeMounts:
        - name: rs256
          mountPath: /RS256
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: auth-microservice-configmap
      volumes:
      - name: rs256
        persistentVolumeClaim:
          claimName: rs256
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
spec:
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        command: ["sleep", "infinity"]
