apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres-svc
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: auth-microservice-svc
  labels:
    app: auth-microservice-svc
spec:
  type: ClusterIP
  selector:
    app: auth-microservice
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: user-microservice-svc
  labels:
    app: user-microservice-svc
spec:
  type: ClusterIP
  selector:
    app: user-microservice
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: user-microservice-v2-svc
  labels:
    app: user-microservice-v2-svc
spec:
  type: ClusterIP
  selector:
    app: user-microservice-v2
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
