apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: local
  istio-injection: enabled

namespace: backend

resources:
  - ../../base

configMapGenerator:
  - name: auth-microservice-configmap
    envs:
      - file/backend.env
    behavior: merge
  - name: postgres-configmap
    envs:
      - file/backend.env
    behavior: merge
